### ISSUE TITLE
开发问题点

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-docs#33]
- action rest 不能直接解析到前台传的文件流，在前台上传时amis上传文件控件可选择使用base64字符串的方式传入rest接口
- 服务端上传文件可调用'~packages-@steedos/service-files.uploadCollectionFile'
- 点击某对象记录列表页按钮获取选中的记录，按钮自定义脚本：
```js
/* 自定义JS使用说明：  
* 1.动作执行函数doAction，可以执行所有类型的动作  
* 2.通过上下文对象context可以获取当前组件实例，例如context.props可以获取该组件相关属性  
* 3.事件对象event，在doAction之后执行event.stopPropagation();可以阻止后续动作执行
*/
const uiSchema = event.data.uiSchema;
const objectName = event.data.objectName;
const listViewRef = event.context.scoped.getComponentById("listview_" + objectName);
const selectedItems = listViewRef && listViewRef.props.store.toJSON().selectedItems || [];
if (selectedItems.length === 0) {
    doAction({ actionType: 'toast', args: { msg: '请至少选择一条记录' } });
    event.stopPropagation();
}
```
- 刷新记录详细页，但不刷新浏览器
```yml
{
    "actionType": "broadcast",
    "args": {
        "eventName": "@data.changed.invoices"
    },
    "data": {
        "objectName": "invoices"
    }
}
```
- 使用amis autoFill 自动给关联字段赋值，如新建银行信息时选择开户银行后自动给联行号赋值，在开户银行字段配置：
```yml
amis:
  autoFill:
    "showSuggestion": false
    "fillMapping": 
      "combinenum": "${combinenum}"
    "api":
      "method": "post"
      "url": "/graphql"
      "data": 
        "query": '{rows:bank(filters: ["_id", "=", "${pk_bankdoc}"]){combinenum}}'
      "silent": false
```
