### ISSUE TITLE
【文档】表单字段联动赋值

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-docs#34]
- 使用amis autoFill 自动给关联字段赋值，如新建银行信息时选择开户银行后自动给联行号(combinenum)赋值，在开户银行字段配置：
```yml
name: pk_bankdoc
label: 开户银行
reference_to: bank
required: true
sort_no: 130
type: lookup
amis:
  autoFill:
    "showSuggestion": false
    "fillMapping": 
      "combinenum": "${combinenum}"
    "api":
      "method": "post"
      "url": "/graphql"
      "data": 
        "query": '{rows:bank(filters: ["_id", "=", "${pk_bankdoc}"]){combinenum}}'
      "silent": false
```
或
```yml
name: pk_bankdoc
label: 开户银行
reference_to: bank
required: true
sort_no: 130
type: lookup
amis:
  autoFill:
    "showSuggestion": false
    "fillMapping": 
      "combinenum": "${combinenum}"
    "api":
      "method": "get"
      "url": "/api/v1/bank/${pk_bankdoc}?fields=[\"combinenum\"]"
      "silent": false
```
或
```yml
name: pk_bankdoc
label: 开户银行
reference_to: bank
required: true
sort_no: 130
type: lookup
amis:
  autoFill:
    "combinenum": "${combinenum}"
```
> 此种写法生效的前提条件为：1、联行号(combinenum)需要显示在相关表(bank)的lookup视图或all视图中；2、相关表(bank)必须启用弹出窗口查找模式

- 根据选择不同的考核类型给最大分值字段自动赋值(选择绩效考核时为30，选择个人评分时为100)
```yml
name: type
label: 考核类型
type: select
options:
  - label: 绩效考核
    value: accessment
  - label: 个人评分
    value: personal
sort_no: 102
amis:
  autoFill:
    "max_score": "${type == 'accessment' ? 30 : 100}"
```
